version: "3.1"


services:
  api_gate:
    build:
      context: ./apiGate
      dockerfile: Dockerfile
    environment:
      PORT: '8081'
    ports:
      - '8081:8081'


  auth_service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    environment:
      PORT: '8001'
    ports:
      - '8001:8001'
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - /home/GolandProjects/posgres/:/posgres/data

  tweet_service:
    build:
      context: ./TweetService
      dockerfile: Dockerfile
    environment:
      PORT: '9092'
    ports:
      - '9092:9092'
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:4.0
    restart: always
    ports:
      - '9042-9042'
    volumes:
      - /home/GolandProjects/cass/:/cass/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10




